commands = {'open_file': [['open', 'file']], 
'youtube_search': [['youtube', 'search']], 
'shuffle_music': [['shuffle', 'music'], ['shuffle', 'song']], 
'google': [['google']], 
'open_editor': [['editor']], 
'save_file': [['save', 'file']], 
'redo': [['redo']], 
'youtube': [['youtube']], 
'screenshot': [['screenshot']], 
'undo': [['undo']], 
'home': [['terminal', 'home']], 
'change_tab': [['change', 'tab']], 
'new_window': [['new', 'window']], 
'search': [['find', 'text'], ['search', 'text'], ['search', 'box'], ['find', 'file'], ['search', 'file']], 
'map': [['map']], 
'delete': [['press', 'delete']], 
'shutdown': [['shutdown', 'computer']], 
'bright_up': [['brightness', 'up'], ['brightness', 'increase']], 
'dictation_mode': [['start', 'dictation', 'mode'], ['on', 'dictation', 'mode']], 
'delete_line': [['delete', 'line']], 
'pause_music': [['pause', 'music'], ['pause', 'song'], ['stop', 'music'], ['stop', 'song']], 
'caps_off': [['caps', 'off'], ['capslock', 'off']], 
'open_doc': [['open', 'documents'], ['file', 'manager', 'documents']], 
'tell_time': [['tell', 'time'], ['what', 'time']], 
'paste': [['paste']], 
'bright_down': [['brightness', 'down'], ['decrease', 'brightness']], 
'close_tab': [['close', 'tab']], 
'convert_to_audio': [['convert', 'audio'], ['convert', 'generated'], ['convert', 'speech'], ['computer', 'generated', 'audio']], 
'copy': [['copy']], 
'tell_year': [['tell', 'year'], ['what', 'year']], 
'zoom_out': [['zoom', 'out']], 
'weather': [['weather', 'search']], 
'random_song': [['random', 'song'], ['random', 'music']], 
'touchpad': [['touchpad']], 
'logoff': [['logoff', 'computer']], 
'tab': [['press', 'tab']], 
'escape': [['press', 'escape']], 
'pic': [['terminal', 'pictures'], ['terminal', 'picture']], 
'wiki_search': [['wiki', 'search'], ['wikipedia', 'search']], 
'select_all': [['select', 'all']], 
'tell_day': [['tell', 'day'], ['what', 'day']], 
'close_window': [['close', 'window']], 
'music_player': [['music', 'player']], 
'whoami': [['who', 'am', 'i']], 
'tell_date': [['tell', 'date'], ['what', 'date']], 
'play_music': [['play', 'music'], ['play', 'song'], ['start', 'music'], ['start', 'song']], 
'open_pic': [['open', 'pictures'], ['file', 'manager', 'pictures']], 
'vol_up': [['increase', 'volume'], ['increase', 'sound'], ['volume', 'up'], ['sound', 'up']], 
'open_terminal': [['terminal']], 
'open_dow': [['open', 'downloads'], ['file', 'manager', 'downloads']], 
'mail': [['open', 'mail']], 
'close_terminal': [['close', 'terminal'], ['exit', 'terminal']], 
'minimize': [['minimize']], 
'prev_song': [['previous', 'music'], ['previous', 'song'], ['last', 'music'], ['last', 'song']], 
'zoom_reset': [['zoom', 'reset']], 
'vol_down': [['decrease', 'volume'], ['decrease', 'sound'], ['volume', 'down'], ['sound', 'down']], 
'open_gedit': [['gedit']], 
'take_picture': [['take', 'picture'],['take', 'photo'],['click', 'photo'], ['click', 'picture']], 
'maximize': [['maximize']], 
'zoom_in': [['zoom', 'in']], 
'enter': [['press', 'enter']], 
'create_folder': [['create', 'folder'], ['new', 'folder']], 
'tell_month': [['tell', 'month'], ['what', 'month']], 
'mute': [['mute', 'sound'], ['mute', 'volume']], 
'open_calc': [['calculator']], 
'dow': [['terminal', 'downloads']], 
'save_as': [['save', 'file', 'as']], 
'cut': [['cut']], 
'new_tab': [['new', 'tab']], 
'open_browser': [['browser']], 
'fullscreen': [['fullscreen']], 
'menu': [['press', 'menu']], 
'caps_on': [['caps', 'on'], ['capslock', 'on']], 
'google_search': [['google', 'search'], ['search', 'online']], 
'open_home': [['file', 'manager', 'home'], ['open', 'home']], 
'next_song': [['change', 'song'], ['change', 'music'], ['next', 'song'], ['next', 'music']], 
'action_menu': [['action', 'menu']], 
'doc': [['terminal', 'documents']], 
'open_file_manager': [['file', 'manager']]}
