priority = {'close_terminal': ['open_terminal'], 
'google_search': ['google', 'search'], 
'open_file_manager': ['open_file', 'save_file'], 
'open_home': ['open_file_manager', 'open_file'], 
'shuffle_music': ['play_music'], 
'dow': ['open_dow', 'open_terminal'], 
'open_doc': ['open_file_manager', 'open_file'], 
'pic': ['open_terminal', 'open_pic', 'take_picture'], 
'prev_song': ['play_music'], 
'open_dow': ['open_file_manager', 'open_file'], 
'next_song': ['play_music'], 
'home': ['open_terminal', 'open_home'], 
'youtube_search': ['youtube', 'search'], 
'open_pic': ['open_file_manager', 'open_file'], 
'doc': ['open_doc', 'open_terminal'], 
'save_as': ['save_file'], 
'random_song': ['play_music'], 
'open_editor': ['open_file']}
